import { CertificateTemplate, CanvasElement, TextElement, ImageElement, BadgeElement, QrCodeElement } from './types';

export const GOOGLE_FONTS = [
  'Montserrat',
  'Cinzel',
  'Playfair Display',
  'Inter',
  'Space Mono',
  'Great Vibes',
  'Alex Brush',
  'Pinyon Script',
  'Italianno',
  'Playball',
  'Parisienne',
  'Tangerine',
  'Sacramento',
  'Allura'
];
export const FONTS_STYLESHEET_URL = 'https://fonts.googleapis.com/css2?family=Alex+Brush&family=Allura&family=Cinzel:wght@500;700&family=Great+Vibes&family=Inter:wght@400;600&family=Italianno&family=Montserrat:wght@400;600;800&family=Parisienne&family=Pinyon+Script&family=Playball&family=Playfair+Display:ital,wght@0,500;0,700;1,400&family=Sacramento&family=Space+Mono&family=Tangerine&display=swap';


export const PREBUILT_TEMPLATES: CertificateTemplate[] = [
  {
    id: 'classic-academic',
    name: 'Classic Academic',
    description: 'A traditional and formal certificate with blue wavy corners and centered elegant layout.',
    category: 'Academic',
    primaryColor: '#0f172a',
    secondaryColor: '#d97706',
    accentColor: '#1e3a8a',
    textColor: '#1e293b',
    fontFamily: 'Cinzel',
    layout: 'landscape',
    fields: ['recipientName', 'courseName', 'date', 'issuerName', 'issuerTitle'],
    styles: {
      backgroundColor: '#fafaf9',
      backgroundType: 'color',
      borderColor: '#0f172a',
      borderWidth: 0,
      borderStyle: 'none',
      accentColor: '#1e3a8a',
    },
    elements: [
      {
        id: 'acad_header',
        type: 'text',
        x: 560,
        y: 155,
        width: 800,
        height: 40,
        visible: true,
        text: 'THE ACADEMY OF EXCELLENCE',
        style: {
          fontSize: 16,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Cinzel',
          color: '#0f172a',
          align: 'center',
          uppercase: true,
          letterSpacing: 4,
        },
        isVariable: false,
      },
      {
        id: 'acad_title',
        type: 'text',
        x: 560,
        y: 230,
        width: 900,
        height: 80,
        visible: true,
        text: 'CERTIFICATE OF ACHIEVEMENT',
        style: {
          fontSize: 38,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Cinzel',
          color: '#0f172a',
          align: 'center',
          uppercase: true,
          letterSpacing: 2,
        },
        isVariable: false,
      },
      {
        id: 'acad_presents',
        type: 'text',
        x: 560,
        y: 320,
        width: 800,
        height: 30,
        visible: true,
        text: 'THIS CERTIFICATE IS PROUDLY PRESENTED TO',
        style: {
          fontSize: 13,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#475569',
          align: 'center',
          uppercase: true,
          letterSpacing: 2,
        },
        isVariable: false,
      },
      {
        id: 'recipientName',
        type: 'text',
        x: 560,
        y: 420,
        width: 850,
        height: 80,
        visible: true,
        text: '{{recipientName}}',
        style: {
          fontSize: 52,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Great Vibes',
          color: '#0f172a',
          align: 'center',
          uppercase: false,
          letterSpacing: 1,
        },
        isVariable: true,
        variableKey: 'recipientName',
      },
      {
        id: 'acad_desc',
        type: 'text',
        x: 560,
        y: 535,
        width: 850,
        height: 80,
        visible: true,
        text: 'for outstanding academic performance, exemplary character, and successfully meeting the requirements for\n{{courseName}}',
        style: {
          fontSize: 14,
          fontWeight: 'normal',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#475569',
          align: 'center',
          uppercase: false,
          letterSpacing: 0.5,
        },
        isVariable: true,
        variableKey: 'courseName',
      },
      {
        id: 'date',
        type: 'text',
        x: 280,
        y: 650,
        width: 250,
        height: 35,
        visible: true,
        text: '{{date}}',
        style: {
          fontSize: 14,
          fontWeight: 'normal',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#0f172a',
          align: 'center',
          uppercase: false,
          letterSpacing: 0,
        },
        isVariable: true,
        variableKey: 'date',
      },
      {
        id: 'acad_date_line',
        type: 'text',
        x: 280,
        y: 690,
        width: 250,
        height: 20,
        visible: true,
        text: 'DATE OF THE CERTIFICATE',
        style: {
          fontSize: 10,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#6b7280',
          align: 'center',
          uppercase: true,
          letterSpacing: 1,
        },
        isVariable: false,
      },
      {
        id: 'issuerName',
        type: 'text',
        x: 840,
        y: 650,
        width: 250,
        height: 35,
        visible: true,
        text: '{{issuerName}}',
        style: {
          fontSize: 15,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Cinzel',
          color: '#0f172a',
          align: 'center',
          uppercase: false,
          letterSpacing: 0,
        },
        isVariable: true,
        variableKey: 'issuerName',
      },
      {
        id: 'issuerTitle',
        type: 'text',
        x: 840,
        y: 690,
        width: 250,
        height: 20,
        visible: true,
        text: '{{issuerTitle}}',
        style: {
          fontSize: 10,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#6b7280',
          align: 'center',
          uppercase: true,
          letterSpacing: 1,
        },
        isVariable: true,
        variableKey: 'issuerTitle',
      },
      {
        id: 'acad_badge',
        type: 'badge',
        x: 560,
        y: 670,
        width: 90,
        height: 90,
        visible: true,
        badgeType: 'laurel_wreath',
        color: '#1e3a8a',
      },
    ],
  },
  {
    id: 'modern-corporate',
    name: 'Modern Corporate',
    description: 'A clean, modern landscape layout with a red side partition and left-aligned text.',
    category: 'Corporate',
    primaryColor: '#7f1d1d',
    secondaryColor: '#ffffff',
    accentColor: '#d97706',
    textColor: '#1f2937',
    fontFamily: 'Montserrat',
    layout: 'landscape',
    fields: ['recipientName', 'courseName', 'date', 'issuerName', 'issuerTitle'],
    styles: {
      backgroundColor: '#ffffff',
      backgroundType: 'color',
      borderColor: '#7f1d1d',
      borderWidth: 0,
      borderStyle: 'none',
      accentColor: '#d97706',
    },
    elements: [
      {
        id: 'corp_header',
        type: 'text',
        x: 420,
        y: 155,
        width: 680,
        height: 30,
        visible: true,
        text: 'GLOBAL TECHNOLOGY CORPORATION',
        style: {
          fontSize: 14,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#d97706',
          align: 'left',
          uppercase: true,
          letterSpacing: 3,
        },
        isVariable: false,
      },
      {
        id: 'corp_title',
        type: 'text',
        x: 420,
        y: 220,
        width: 680,
        height: 75,
        visible: true,
        text: 'CERTIFICATE OF COMPLIANCE',
        style: {
          fontSize: 34,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#1e3a8a',
          align: 'left',
          uppercase: true,
          letterSpacing: 2,
        },
        isVariable: false,
      },
      {
        id: 'corp_presents',
        type: 'text',
        x: 420,
        y: 310,
        width: 680,
        height: 30,
        visible: true,
        text: 'This certificate is proudly presented to',
        style: {
          fontSize: 14,
          fontWeight: 'normal',
          fontStyle: 'italic',
          fontFamily: 'Inter',
          color: '#4b5563',
          align: 'left',
          uppercase: false,
          letterSpacing: 0,
        },
        isVariable: false,
      },
      {
        id: 'recipientName',
        type: 'text',
        x: 420,
        y: 400,
        width: 680,
        height: 80,
        visible: true,
        text: '{{recipientName}}',
        style: {
          fontSize: 48,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Pinyon Script',
          color: '#1e3a8a',
          align: 'left',
          uppercase: false,
          letterSpacing: 1,
        },
        isVariable: true,
        variableKey: 'recipientName',
      },
      {
        id: 'corp_desc',
        type: 'text',
        x: 420,
        y: 515,
        width: 680,
        height: 80,
        visible: true,
        text: 'for demonstrating outstanding professional standards, compliance with institutional values, and successful completion of\n{{courseName}}',
        style: {
          fontSize: 13,
          fontWeight: 'normal',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#4b5563',
          align: 'left',
          uppercase: false,
          letterSpacing: 0.5,
        },
        isVariable: true,
        variableKey: 'courseName',
      },
      {
        id: 'date',
        type: 'text',
        x: 230,
        y: 660,
        width: 220,
        height: 30,
        visible: true,
        text: '{{date}}',
        style: {
          fontSize: 14,
          fontWeight: 'normal',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#111827',
          align: 'center',
          uppercase: false,
          letterSpacing: 0,
        },
        isVariable: true,
        variableKey: 'date',
      },
      {
        id: 'corp_date_line',
        type: 'text',
        x: 230,
        y: 695,
        width: 220,
        height: 20,
        visible: true,
        text: 'DATE OF THE CERTIFICATE',
        style: {
          fontSize: 10,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#9ca3af',
          align: 'center',
          uppercase: true,
          letterSpacing: 1,
        },
        isVariable: false,
      },
      {
        id: 'issuerName',
        type: 'text',
        x: 580,
        y: 660,
        width: 220,
        height: 30,
        visible: true,
        text: '{{issuerName}}',
        style: {
          fontSize: 15,
          fontWeight: 'semibold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#111827',
          align: 'center',
          uppercase: false,
          letterSpacing: 0,
        },
        isVariable: true,
        variableKey: 'issuerName',
      },
      {
        id: 'issuerTitle',
        type: 'text',
        x: 580,
        y: 695,
        width: 220,
        height: 20,
        visible: true,
        text: '{{issuerTitle}}',
        style: {
          fontSize: 10,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#9ca3af',
          align: 'center',
          uppercase: true,
          letterSpacing: 1,
        },
        isVariable: true,
        variableKey: 'issuerTitle',
      },
      {
        id: 'corp_badge',
        type: 'badge',
        x: 960,
        y: 220,
        width: 140,
        height: 140,
        visible: true,
        badgeType: 'gold_seal',
        color: '#d97706',
      },
    ],
  },
  {
    id: 'achievement-award',
    name: 'Achievement Award',
    description: 'An elegant award certificate with a gold Intricate ornate border and classic typography.',
    category: 'Award',
    primaryColor: '#78350f',
    secondaryColor: '#ffffff',
    accentColor: '#b45309',
    textColor: '#1e293b',
    fontFamily: 'Cinzel',
    layout: 'landscape',
    fields: ['recipientName', 'courseName', 'date', 'issuerName', 'issuerTitle'],
    styles: {
      backgroundColor: '#fafaf9',
      backgroundType: 'color',
      borderColor: '#b45309',
      borderWidth: 0,
      borderStyle: 'none',
      accentColor: '#b45309',
    },
    elements: [
      {
        id: 'ach_header',
        type: 'text',
        x: 560,
        y: 160,
        width: 800,
        height: 30,
        visible: true,
        text: 'HONOR SOCIETY OF OUTSTANDING MERIT',
        style: {
          fontSize: 14,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#78350f',
          align: 'center',
          uppercase: true,
          letterSpacing: 3,
        },
        isVariable: false,
      },
      {
        id: 'ach_title',
        type: 'text',
        x: 560,
        y: 230,
        width: 900,
        height: 80,
        visible: true,
        text: 'CERTIFICATE OF ACHIEVEMENT',
        style: {
          fontSize: 38,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Cinzel',
          color: '#78350f',
          align: 'center',
          uppercase: true,
          letterSpacing: 1.5,
        },
        isVariable: false,
      },
      {
        id: 'ach_presents',
        type: 'text',
        x: 560,
        y: 320,
        width: 800,
        height: 30,
        visible: true,
        text: 'THIS CERTIFICATE IS PROUDLY PRESENTED FOR HONORABLE ACHIEVEMENT TO',
        style: {
          fontSize: 12,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Cinzel',
          color: '#4b5563',
          align: 'center',
          uppercase: true,
          letterSpacing: 1.5,
        },
        isVariable: false,
      },
      {
        id: 'recipientName',
        type: 'text',
        x: 560,
        y: 420,
        width: 850,
        height: 80,
        visible: true,
        text: '{{recipientName}}',
        style: {
          fontSize: 50,
          fontWeight: 'bold',
          fontStyle: 'italic',
          fontFamily: 'Playfair Display',
          color: '#78350f',
          align: 'center',
          uppercase: false,
          letterSpacing: 1,
        },
        isVariable: true,
        variableKey: 'recipientName',
      },
      {
        id: 'ach_desc',
        type: 'text',
        x: 560,
        y: 535,
        width: 850,
        height: 80,
        visible: true,
        text: 'in recognition of outstanding service, stellar work ethic, and peerless contributions to\n{{courseName}}',
        style: {
          fontSize: 13,
          fontWeight: 'normal',
          fontStyle: 'italic',
          fontFamily: 'Playfair Display',
          color: '#475569',
          align: 'center',
          uppercase: false,
          letterSpacing: 0.5,
        },
        isVariable: true,
        variableKey: 'courseName',
      },
      {
        id: 'date',
        type: 'text',
        x: 280,
        y: 660,
        width: 250,
        height: 30,
        visible: true,
        text: '{{date}}',
        style: {
          fontSize: 14,
          fontWeight: 'normal',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#111827',
          align: 'center',
          uppercase: false,
          letterSpacing: 0,
        },
        isVariable: true,
        variableKey: 'date',
      },
      {
        id: 'ach_date_line',
        type: 'text',
        x: 280,
        y: 695,
        width: 250,
        height: 20,
        visible: true,
        text: 'DATE OF THE CERTIFICATE',
        style: {
          fontSize: 10,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#9ca3af',
          align: 'center',
          uppercase: true,
          letterSpacing: 1,
        },
        isVariable: false,
      },
      {
        id: 'issuerName',
        type: 'text',
        x: 840,
        y: 660,
        width: 250,
        height: 30,
        visible: true,
        text: '{{issuerName}}',
        style: {
          fontSize: 15,
          fontWeight: 'semibold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#111827',
          align: 'center',
          uppercase: false,
          letterSpacing: 0,
        },
        isVariable: true,
        variableKey: 'issuerName',
      },
      {
        id: 'issuerTitle',
        type: 'text',
        x: 840,
        y: 695,
        width: 250,
        height: 20,
        visible: true,
        text: '{{issuerTitle}}',
        style: {
          fontSize: 10,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#9ca3af',
          align: 'center',
          uppercase: true,
          letterSpacing: 1,
        },
        isVariable: true,
        variableKey: 'issuerTitle',
      },
      {
        id: 'ach_badge',
        type: 'badge',
        x: 560,
        y: 670,
        width: 95,
        height: 95,
        visible: true,
        badgeType: 'shield',
        color: '#b45309',
      },
    ],
  },
  {
    id: 'participation-badge',
    name: 'Participation Badge',
    description: 'A certificate with sleek black and gold corner geometry and gold laurel badge.',
    category: 'Award',
    primaryColor: '#111827',
    secondaryColor: '#ffffff',
    accentColor: '#d97706',
    textColor: '#1e293b',
    fontFamily: 'Inter',
    layout: 'landscape',
    fields: ['recipientName', 'courseName', 'date', 'issuerName', 'issuerTitle'],
    styles: {
      backgroundColor: '#fafaf9',
      backgroundType: 'color',
      borderColor: '#d97706',
      borderWidth: 0,
      borderStyle: 'none',
      accentColor: '#d97706',
    },
    elements: [
      {
        id: 'part_header',
        type: 'text',
        x: 560,
        y: 155,
        width: 800,
        height: 30,
        visible: true,
        text: 'COMMUNITY & INVOLVEMENT SERIES',
        style: {
          fontSize: 13,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#111827',
          align: 'center',
          uppercase: true,
          letterSpacing: 3,
        },
        isVariable: false,
      },
      {
        id: 'part_title',
        type: 'text',
        x: 560,
        y: 220,
        width: 900,
        height: 75,
        visible: true,
        text: 'CERTIFICATE OF APPRECIATION',
        style: {
          fontSize: 36,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#d97706',
          align: 'center',
          uppercase: true,
          letterSpacing: 2,
        },
        isVariable: false,
      },
      {
        id: 'part_presents',
        type: 'text',
        x: 560,
        y: 310,
        width: 800,
        height: 30,
        visible: true,
        text: 'THE FOLLOWING AWARD IS GIVEN TO',
        style: {
          fontSize: 12,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#4b5563',
          align: 'center',
          uppercase: true,
          letterSpacing: 1,
        },
        isVariable: false,
      },
      {
        id: 'recipientName',
        type: 'text',
        x: 560,
        y: 410,
        width: 850,
        height: 80,
        visible: true,
        text: '{{recipientName}}',
        style: {
          fontSize: 50,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Great Vibes',
          color: '#111827',
          align: 'center',
          uppercase: false,
          letterSpacing: 1,
        },
        isVariable: true,
        variableKey: 'recipientName',
      },
      {
        id: 'part_desc',
        type: 'text',
        x: 560,
        y: 525,
        width: 850,
        height: 80,
        visible: true,
        text: 'This certificate is given to {{recipientName}} for their outstanding achievements in the field of education and proves competency in\n{{courseName}}',
        style: {
          fontSize: 14,
          fontWeight: 'normal',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#475569',
          align: 'center',
          uppercase: false,
          letterSpacing: 0.5,
        },
        isVariable: true,
        variableKey: 'courseName',
      },
      {
        id: 'date',
        type: 'text',
        x: 280,
        y: 650,
        width: 250,
        height: 30,
        visible: true,
        text: '{{date}}',
        style: {
          fontSize: 14,
          fontWeight: 'normal',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#111827',
          align: 'center',
          uppercase: false,
          letterSpacing: 0,
        },
        isVariable: true,
        variableKey: 'date',
      },
      {
        id: 'part_date_line',
        type: 'text',
        x: 280,
        y: 685,
        width: 250,
        height: 20,
        visible: true,
        text: 'DATE OF THE CERTIFICATE',
        style: {
          fontSize: 10,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#94a3b8',
          align: 'center',
          uppercase: true,
          letterSpacing: 1,
        },
        isVariable: false,
      },
      {
        id: 'issuerName',
        type: 'text',
        x: 840,
        y: 650,
        width: 250,
        height: 30,
        visible: true,
        text: '{{issuerName}}',
        style: {
          fontSize: 15,
          fontWeight: 'semibold',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#111827',
          align: 'center',
          uppercase: false,
          letterSpacing: 0,
        },
        isVariable: true,
        variableKey: 'issuerName',
      },
      {
        id: 'issuerTitle',
        type: 'text',
        x: 840,
        y: 685,
        width: 250,
        height: 20,
        visible: true,
        text: '{{issuerTitle}}',
        style: {
          fontSize: 10,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#94a3b8',
          align: 'center',
          uppercase: true,
          letterSpacing: 1,
        },
        isVariable: true,
        variableKey: 'issuerTitle',
      },
      {
        id: 'part_badge',
        type: 'badge',
        x: 560,
        y: 670,
        width: 85,
        height: 85,
        visible: true,
        badgeType: 'laurel_wreath',
        color: '#d97706',
      },
    ],
  },
  {
    id: 'excellence-award',
    name: 'Excellence Award',
    description: 'A premium navy blue and gold geometric award for distinguished achievements.',
    category: 'Award',
    primaryColor: '#1e3a8a',
    secondaryColor: '#ffffff',
    accentColor: '#d97706',
    textColor: '#1e293b',
    fontFamily: 'Playfair Display',
    layout: 'landscape',
    fields: ['recipientName', 'courseName', 'date', 'issuerName', 'issuerTitle'],
    styles: {
      backgroundColor: '#ffffff',
      backgroundType: 'color',
      borderColor: '#1e3a8a',
      borderWidth: 0,
      borderStyle: 'none',
      accentColor: '#d97706',
    },
    elements: [
      {
        id: 'exc_header',
        type: 'text',
        x: 560,
        y: 155,
        width: 800,
        height: 30,
        visible: true,
        text: 'ACADEME & PROFESSIONAL HONORS',
        style: {
          fontSize: 13,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#1e3a8a',
          align: 'center',
          uppercase: true,
          letterSpacing: 3,
        },
        isVariable: false,
      },
      {
        id: 'exc_title',
        type: 'text',
        x: 560,
        y: 220,
        width: 900,
        height: 75,
        visible: true,
        text: 'CERTIFICATE OF APPRECIATION',
        style: {
          fontSize: 36,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#1e3a8a',
          align: 'center',
          uppercase: true,
          letterSpacing: 2,
        },
        isVariable: false,
      },
      {
        id: 'exc_presents',
        type: 'text',
        x: 560,
        y: 310,
        width: 800,
        height: 30,
        visible: true,
        text: 'PROUDLY PRESENTED TO',
        style: {
          fontSize: 12,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#d97706',
          align: 'center',
          uppercase: true,
          letterSpacing: 1.5,
        },
        isVariable: false,
      },
      {
        id: 'recipientName',
        type: 'text',
        x: 560,
        y: 410,
        width: 850,
        height: 80,
        visible: true,
        text: '{{recipientName}}',
        style: {
          fontSize: 50,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Playball',
          color: '#1e3a8a',
          align: 'center',
          uppercase: false,
          letterSpacing: 1,
        },
        isVariable: true,
        variableKey: 'recipientName',
      },
      {
        id: 'exc_desc',
        type: 'text',
        x: 560,
        y: 525,
        width: 850,
        height: 80,
        visible: true,
        text: 'for demonstrating outstanding performance, exceptional work ethic, and peerless dedication during the completion of\n{{courseName}}',
        style: {
          fontSize: 14,
          fontWeight: 'normal',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#1e293b',
          align: 'center',
          uppercase: false,
          letterSpacing: 0.5,
        },
        isVariable: true,
        variableKey: 'courseName',
      },
      {
        id: 'date',
        type: 'text',
        x: 280,
        y: 650,
        width: 250,
        height: 30,
        visible: true,
        text: '{{date}}',
        style: {
          fontSize: 14,
          fontWeight: 'normal',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#1e293b',
          align: 'center',
          uppercase: false,
          letterSpacing: 0,
        },
        isVariable: true,
        variableKey: 'date',
      },
      {
        id: 'exc_date_line',
        type: 'text',
        x: 280,
        y: 685,
        width: 250,
        height: 20,
        visible: true,
        text: 'DATE OF THE CERTIFICATE',
        style: {
          fontSize: 10,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#1e3a8a',
          align: 'center',
          uppercase: true,
          letterSpacing: 1,
        },
        isVariable: false,
      },
      {
        id: 'issuerName',
        type: 'text',
        x: 840,
        y: 650,
        width: 250,
        height: 30,
        visible: true,
        text: '{{issuerName}}',
        style: {
          fontSize: 15,
          fontWeight: 'semibold',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#1e293b',
          align: 'center',
          uppercase: false,
          letterSpacing: 0,
        },
        isVariable: true,
        variableKey: 'issuerName',
      },
      {
        id: 'issuerTitle',
        type: 'text',
        x: 840,
        y: 685,
        width: 250,
        height: 20,
        visible: true,
        text: '{{issuerTitle}}',
        style: {
          fontSize: 10,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#1e3a8a',
          align: 'center',
          uppercase: true,
          letterSpacing: 1,
        },
        isVariable: true,
        variableKey: 'issuerTitle',
      },
      {
        id: 'exc_badge',
        type: 'badge',
        x: 560,
        y: 670,
        width: 85,
        height: 85,
        visible: true,
        badgeType: 'gold_seal',
        color: '#d97706',
      },
    ],
  },
  {
    id: 'training-completion',
    name: 'Training Completion',
    description: 'A landscape template with navy & gold geometric corners, wavy side lines, and a central badge.',
    category: 'Corporate',
    primaryColor: '#0f172a',
    secondaryColor: '#ffffff',
    accentColor: '#eab308',
    textColor: '#1e293b',
    fontFamily: 'Playfair Display',
    layout: 'landscape',
    fields: ['recipientName', 'courseName', 'date', 'issuerName', 'issuerTitle'],
    styles: {
      backgroundColor: '#ffffff',
      backgroundType: 'color',
      borderColor: '#0f172a',
      borderWidth: 0,
      borderStyle: 'none',
      accentColor: '#eab308',
    },
    elements: [
      {
        id: 'train_header',
        type: 'text',
        x: 560,
        y: 155,
        width: 800,
        height: 30,
        visible: true,
        text: 'PROFESSIONAL TRAINING SYSTEMS',
        style: {
          fontSize: 14,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#eab308',
          align: 'center',
          uppercase: true,
          letterSpacing: 3,
        },
        isVariable: false,
      },
      {
        id: 'train_title',
        type: 'text',
        x: 560,
        y: 220,
        width: 900,
        height: 60,
        visible: true,
        text: 'Certificate of Achievement',
        style: {
          fontSize: 38,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Playfair Display',
          color: '#0f172a',
          align: 'center',
          uppercase: false,
          letterSpacing: 1.5,
        },
        isVariable: false,
      },
      {
        id: 'train_presents',
        type: 'text',
        x: 560,
        y: 310,
        width: 800,
        height: 30,
        visible: true,
        text: 'This certificate is proudly awarded to',
        style: {
          fontSize: 15,
          fontWeight: 'normal',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#475569',
          align: 'center',
          uppercase: false,
          letterSpacing: 0,
        },
        isVariable: false,
      },
      {
        id: 'recipientName',
        type: 'text',
        x: 560,
        y: 410,
        width: 800,
        height: 70,
        visible: true,
        text: '{{recipientName}}',
        style: {
          fontSize: 52,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Great Vibes',
          color: '#0f172a',
          align: 'center',
          uppercase: false,
          letterSpacing: 1,
        },
        isVariable: true,
        variableKey: 'recipientName',
      },
      {
        id: 'train_desc',
        type: 'text',
        x: 560,
        y: 520,
        width: 800,
        height: 80,
        visible: true,
        text: 'for successfully completing the standard curriculum and assessments required for\n{{courseName}}',
        style: {
          fontSize: 14,
          fontWeight: 'normal',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#475569',
          align: 'center',
          uppercase: false,
          letterSpacing: 0.5,
        },
        isVariable: true,
        variableKey: 'courseName',
      },
      {
        id: 'date',
        type: 'text',
        x: 280,
        y: 650,
        width: 250,
        height: 30,
        visible: true,
        text: '{{date}}',
        style: {
          fontSize: 14,
          fontWeight: 'normal',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#0f172a',
          align: 'center',
          uppercase: false,
          letterSpacing: 0,
        },
        isVariable: true,
        variableKey: 'date',
      },
      {
        id: 'train_date_line',
        type: 'text',
        x: 280,
        y: 690,
        width: 250,
        height: 20,
        visible: true,
        text: 'DATE OF THE CERTIFICATE',
        style: {
          fontSize: 10,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#94a3b8',
          align: 'center',
          uppercase: true,
          letterSpacing: 1,
        },
        isVariable: false,
      },
      {
        id: 'issuerName',
        type: 'text',
        x: 840,
        y: 650,
        width: 250,
        height: 30,
        visible: true,
        text: '{{issuerName}}',
        style: {
          fontSize: 15,
          fontWeight: 'semibold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#0f172a',
          align: 'center',
          uppercase: false,
          letterSpacing: 0,
        },
        isVariable: true,
        variableKey: 'issuerName',
      },
      {
        id: 'issuerTitle',
        type: 'text',
        x: 840,
        y: 690,
        width: 250,
        height: 20,
        visible: true,
        text: '{{issuerTitle}}',
        style: {
          fontSize: 10,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#94a3b8',
          align: 'center',
          uppercase: true,
          letterSpacing: 1,
        },
        isVariable: true,
        variableKey: 'issuerTitle',
      },
      {
        id: 'train_badge',
        type: 'badge',
        x: 560,
        y: 670,
        width: 90,
        height: 90,
        visible: true,
        badgeType: 'laurel_wreath',
        color: '#eab308',
      },
    ],
  },
  {
    id: 'leadership-award',
    name: 'Leadership Award',
    description: 'A clean, modern layout with a navy blue ribbon panel on the left and double gold border.',
    category: 'Award',
    primaryColor: '#1e3a8a',
    secondaryColor: '#ffffff',
    accentColor: '#d97706',
    textColor: '#1f2937',
    fontFamily: 'Montserrat',
    layout: 'landscape',
    fields: ['recipientName', 'courseName', 'date', 'issuerName', 'issuerTitle'],
    styles: {
      backgroundColor: '#ffffff',
      backgroundType: 'color',
      borderColor: '#1e3a8a',
      borderWidth: 0,
      borderStyle: 'none',
      accentColor: '#d97706',
    },
    elements: [
      {
        id: 'lead_header',
        type: 'text',
        x: 420,
        y: 160,
        width: 640,
        height: 30,
        visible: true,
        text: 'LEADERSHIP EXCELLENCE CONSORTIUM',
        style: {
          fontSize: 13,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#d97706',
          align: 'left',
          uppercase: true,
          letterSpacing: 3,
        },
        isVariable: false,
      },
      {
        id: 'lead_title',
        type: 'text',
        x: 420,
        y: 230,
        width: 680,
        height: 60,
        visible: true,
        text: 'CERTIFICATE OF ACHIEVEMENT',
        style: {
          fontSize: 34,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#1e3a8a',
          align: 'left',
          uppercase: true,
          letterSpacing: 1.5,
        },
        isVariable: false,
      },
      {
        id: 'lead_presents',
        type: 'text',
        x: 420,
        y: 320,
        width: 640,
        height: 30,
        visible: true,
        text: 'THIS CERTIFICATE IS PROUDLY PRESENTED TO',
        style: {
          fontSize: 12,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#4b5563',
          align: 'left',
          uppercase: true,
          letterSpacing: 1,
        },
        isVariable: false,
      },
      {
        id: 'recipientName',
        type: 'text',
        x: 420,
        y: 420,
        width: 680,
        height: 70,
        visible: true,
        text: '{{recipientName}}',
        style: {
          fontSize: 48,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Pinyon Script',
          color: '#1e3a8a',
          align: 'left',
          uppercase: false,
          letterSpacing: 1,
        },
        isVariable: true,
        variableKey: 'recipientName',
      },
      {
        id: 'lead_desc',
        type: 'text',
        x: 420,
        y: 530,
        width: 680,
        height: 80,
        visible: true,
        text: 'in recognition of outstanding service, stellar work ethic, and successful completion of\n{{courseName}}',
        style: {
          fontSize: 13,
          fontWeight: 'normal',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#475569',
          align: 'left',
          uppercase: false,
          letterSpacing: 0.5,
        },
        isVariable: true,
        variableKey: 'courseName',
      },
      {
        id: 'date',
        type: 'text',
        x: 500,
        y: 660,
        width: 200,
        height: 30,
        visible: true,
        text: '{{date}}',
        style: {
          fontSize: 14,
          fontWeight: 'normal',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#1f2937',
          align: 'center',
          uppercase: false,
          letterSpacing: 0,
        },
        isVariable: true,
        variableKey: 'date',
      },
      {
        id: 'lead_date_line',
        type: 'text',
        x: 500,
        y: 695,
        width: 200,
        height: 20,
        visible: true,
        text: 'DATE OF THE CERTIFICATE',
        style: {
          fontSize: 10,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#9ca3af',
          align: 'center',
          uppercase: true,
          letterSpacing: 1,
        },
        isVariable: false,
      },
      {
        id: 'issuerName',
        type: 'text',
        x: 850,
        y: 660,
        width: 200,
        height: 30,
        visible: true,
        text: '{{issuerName}}',
        style: {
          fontSize: 15,
          fontWeight: 'semibold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#1f2937',
          align: 'center',
          uppercase: false,
          letterSpacing: 0,
        },
        isVariable: true,
        variableKey: 'issuerName',
      },
      {
        id: 'issuerTitle',
        type: 'text',
        x: 850,
        y: 695,
        width: 200,
        height: 20,
        visible: true,
        text: '{{issuerTitle}}',
        style: {
          fontSize: 10,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#9ca3af',
          align: 'center',
          uppercase: true,
          letterSpacing: 1,
        },
        isVariable: true,
        variableKey: 'issuerTitle',
      },
      {
        id: 'lead_badge',
        type: 'badge',
        x: 200,
        y: 250,
        width: 130,
        height: 130,
        visible: true,
        badgeType: 'gold_seal',
        color: '#d97706',
      },
    ],
  },
  {
    id: 'appreciation-cert',
    name: 'Appreciation Warm Cream',
    description: 'An elegant award template with a navy border, thin gold ornate corners, and a concentric wave background.',
    category: 'Award',
    primaryColor: '#0f172a',
    secondaryColor: '#ffffff',
    accentColor: '#b45309',
    textColor: '#1e293b',
    fontFamily: 'Playfair Display',
    layout: 'landscape',
    fields: ['recipientName', 'courseName', 'date', 'issuerName', 'issuerTitle'],
    styles: {
      backgroundColor: '#ffffff',
      backgroundType: 'color',
      borderColor: '#0f172a',
      borderWidth: 0,
      borderStyle: 'none',
      accentColor: '#b45309',
    },
    elements: [
      {
        id: 'app_header',
        type: 'text',
        x: 560,
        y: 160,
        width: 800,
        height: 30,
        visible: true,
        text: 'IN GRATITUDE AND RECOGNITION',
        style: {
          fontSize: 13,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#b45309',
          align: 'center',
          uppercase: true,
          letterSpacing: 3,
        },
        isVariable: false,
      },
      {
        id: 'app_title',
        type: 'text',
        x: 560,
        y: 230,
        width: 900,
        height: 70,
        visible: true,
        text: 'CERTIFICATE OF ACHIEVEMENT',
        style: {
          fontSize: 38,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Cinzel',
          color: '#b45309',
          align: 'center',
          uppercase: true,
          letterSpacing: 1.5,
        },
        isVariable: false,
      },
      {
        id: 'app_presents',
        type: 'text',
        x: 560,
        y: 320,
        width: 800,
        height: 30,
        visible: true,
        text: 'This certificate is proudly presented for honorable achievement to',
        style: {
          fontSize: 15,
          fontWeight: 'normal',
          fontStyle: 'italic',
          fontFamily: 'Playfair Display',
          color: '#475569',
          align: 'center',
          uppercase: false,
          letterSpacing: 0,
        },
        isVariable: false,
      },
      {
        id: 'recipientName',
        type: 'text',
        x: 560,
        y: 420,
        width: 850,
        height: 75,
        visible: true,
        text: '{{recipientName}}',
        style: {
          fontSize: 50,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Playfair Display',
          color: '#b45309',
          align: 'center',
          uppercase: false,
          letterSpacing: 1,
        },
        isVariable: true,
        variableKey: 'recipientName',
      },
      {
        id: 'app_desc',
        type: 'text',
        x: 560,
        y: 530,
        width: 850,
        height: 90,
        visible: true,
        text: 'in recognition of invaluable services, dedicated commitment, and excellent cooperation rendered toward the success of\n{{courseName}}',
        style: {
          fontSize: 14,
          fontWeight: 'normal',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#475569',
          align: 'center',
          uppercase: false,
          letterSpacing: 0.5,
        },
        isVariable: true,
        variableKey: 'courseName',
      },
      {
        id: 'date',
        type: 'text',
        x: 280,
        y: 650,
        width: 250,
        height: 35,
        visible: true,
        text: '{{date}}',
        style: {
          fontSize: 14,
          fontWeight: 'normal',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#0f172a',
          align: 'center',
          uppercase: false,
          letterSpacing: 0,
        },
        isVariable: true,
        variableKey: 'date',
      },
      {
        id: 'app_date_line',
        type: 'text',
        x: 280,
        y: 690,
        width: 250,
        height: 20,
        visible: true,
        text: 'DATE OF THE CERTIFICATE',
        style: {
          fontSize: 10,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#b45309',
          align: 'center',
          uppercase: true,
          letterSpacing: 1,
        },
        isVariable: false,
      },
      {
        id: 'issuerName',
        type: 'text',
        x: 840,
        y: 650,
        width: 250,
        height: 35,
        visible: true,
        text: '{{issuerName}}',
        style: {
          fontSize: 15,
          fontWeight: 'semibold',
          fontStyle: 'normal',
          fontFamily: 'Playfair Display',
          color: '#0f172a',
          align: 'center',
          uppercase: false,
          letterSpacing: 0,
        },
        isVariable: true,
        variableKey: 'issuerName',
      },
      {
        id: 'issuerTitle',
        type: 'text',
        x: 840,
        y: 690,
        width: 250,
        height: 20,
        visible: true,
        text: '{{issuerTitle}}',
        style: {
          fontSize: 10,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#b45309',
          align: 'center',
          uppercase: true,
          letterSpacing: 1,
        },
        isVariable: true,
        variableKey: 'issuerTitle',
      },
      {
        id: 'app_badge',
        type: 'badge',
        x: 560,
        y: 715,
        width: 90,
        height: 90,
        visible: true,
        badgeType: 'laurel_wreath',
        color: '#b45309',
      },
    ],
  },
  {
    id: 'professional-dev',
    name: 'Professional Development',
    description: 'A dynamic, modern layout featuring curved navy and gold shapes in the top-left and bottom-right corners.',
    category: 'Corporate',
    primaryColor: '#0f172a',
    secondaryColor: '#ffffff',
    accentColor: '#d97706',
    textColor: '#1e293b',
    fontFamily: 'Inter',
    layout: 'landscape',
    fields: ['recipientName', 'courseName', 'date', 'issuerName', 'issuerTitle'],
    styles: {
      backgroundColor: '#ffffff',
      backgroundType: 'color',
      borderColor: '#0f172a',
      borderWidth: 0,
      borderStyle: 'none',
      accentColor: '#d97706',
    },
    elements: [
      {
        id: 'prof_header',
        type: 'text',
        x: 560,
        y: 160,
        width: 800,
        height: 30,
        visible: true,
        text: 'CENTER FOR EXECUTIVE EDUCATION',
        style: {
          fontSize: 13,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#d97706',
          align: 'center',
          uppercase: true,
          letterSpacing: 3,
        },
        isVariable: false,
      },
      {
        id: 'prof_title',
        type: 'text',
        x: 560,
        y: 230,
        width: 900,
        height: 60,
        visible: true,
        text: 'CERTIFICATE OF APPRECIATION',
        style: {
          fontSize: 36,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Cinzel',
          color: '#0f172a',
          align: 'center',
          uppercase: true,
          letterSpacing: 1.5,
        },
        isVariable: false,
      },
      {
        id: 'prof_presents',
        type: 'text',
        x: 560,
        y: 320,
        width: 800,
        height: 30,
        visible: true,
        text: 'PROUDLY PRESENTED TO',
        style: {
          fontSize: 14,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#d97706',
          align: 'center',
          uppercase: true,
          letterSpacing: 1.5,
        },
        isVariable: false,
      },
      {
        id: 'recipientName',
        type: 'text',
        x: 560,
        y: 420,
        width: 800,
        height: 70,
        visible: true,
        text: '{{recipientName}}',
        style: {
          fontSize: 52,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Great Vibes',
          color: '#0f172a',
          align: 'center',
          uppercase: false,
          letterSpacing: 1,
        },
        isVariable: true,
        variableKey: 'recipientName',
      },
      {
        id: 'prof_desc',
        type: 'text',
        x: 560,
        y: 530,
        width: 800,
        height: 80,
        visible: true,
        text: 'for active participation, professional excellence, and commitment to lifelong learning through the seminar\n{{courseName}}',
        style: {
          fontSize: 14,
          fontWeight: 'normal',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#64748b',
          align: 'center',
          uppercase: false,
          letterSpacing: 0.5,
        },
        isVariable: true,
        variableKey: 'courseName',
      },
      {
        id: 'date',
        type: 'text',
        x: 280,
        y: 650,
        width: 250,
        height: 30,
        visible: true,
        text: '{{date}}',
        style: {
          fontSize: 14,
          fontWeight: 'normal',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#0f172a',
          align: 'center',
          uppercase: false,
          letterSpacing: 0,
        },
        isVariable: true,
        variableKey: 'date',
      },
      {
        id: 'prof_date_line',
        type: 'text',
        x: 280,
        y: 690,
        width: 250,
        height: 20,
        visible: true,
        text: 'DATE OF THE CERTIFICATE',
        style: {
          fontSize: 10,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#94a3b8',
          align: 'center',
          uppercase: true,
          letterSpacing: 1,
        },
        isVariable: false,
      },
      {
        id: 'issuerName',
        type: 'text',
        x: 840,
        y: 650,
        width: 250,
        height: 30,
        visible: true,
        text: '{{issuerName}}',
        style: {
          fontSize: 15,
          fontWeight: 'semibold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#0f172a',
          align: 'center',
          uppercase: false,
          letterSpacing: 0,
        },
        isVariable: true,
        variableKey: 'issuerName',
      },
      {
        id: 'issuerTitle',
        type: 'text',
        x: 840,
        y: 690,
        width: 250,
        height: 20,
        visible: true,
        text: '{{issuerTitle}}',
        style: {
          fontSize: 10,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#94a3b8',
          align: 'center',
          uppercase: true,
          letterSpacing: 1,
        },
        isVariable: true,
        variableKey: 'issuerTitle',
      },
      {
        id: 'prof_badge',
        type: 'badge',
        x: 560,
        y: 670,
        width: 90,
        height: 90,
        visible: true,
        badgeType: 'shield',
        color: '#d97706',
      },
    ],
  },
  {
    id: 'minimal-blank',
    name: 'Minimalist Blank Canvas',
    description: 'An elegant template with a dark border, gold curved corner details, a dotted grid, and a top-right congrats seal.',
    category: 'General',
    primaryColor: '#111827',
    secondaryColor: '#ffffff',
    accentColor: '#eab308',
    textColor: '#1f2937',
    fontFamily: 'Playball',
    layout: 'landscape',
    fields: ['recipientName', 'courseName', 'date', 'issuerName', 'issuerTitle'],
    styles: {
      backgroundColor: '#ffffff',
      backgroundType: 'color',
      borderColor: '#111827',
      borderWidth: 0,
      borderStyle: 'none',
      accentColor: '#eab308',
    },
    elements: [
      {
        id: 'min_header',
        type: 'text',
        x: 560,
        y: 160,
        width: 800,
        height: 30,
        visible: true,
        text: 'CERTIFICATE OF ACHIEVEMENT',
        style: {
          fontSize: 13,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#eab308',
          align: 'center',
          uppercase: true,
          letterSpacing: 4,
        },
        isVariable: false,
      },
      {
        id: 'min_title',
        type: 'text',
        x: 560,
        y: 240,
        width: 900,
        height: 60,
        visible: true,
        text: 'CERTIFICATE OF ACHIEVEMENT',
        style: {
          fontSize: 36,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Cinzel',
          color: '#111827',
          align: 'center',
          uppercase: true,
          letterSpacing: 2,
        },
        isVariable: false,
      },
      {
        id: 'min_presents',
        type: 'text',
        x: 560,
        y: 330,
        width: 800,
        height: 30,
        visible: true,
        text: 'This certificate is awarded to',
        style: {
          fontSize: 15,
          fontWeight: 'normal',
          fontStyle: 'italic',
          fontFamily: 'Playfair Display',
          color: '#64748b',
          align: 'center',
          uppercase: false,
          letterSpacing: 0,
        },
        isVariable: false,
      },
      {
        id: 'recipientName',
        type: 'text',
        x: 560,
        y: 430,
        width: 800,
        height: 70,
        visible: true,
        text: '{{recipientName}}',
        style: {
          fontSize: 50,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Playball',
          color: '#111827',
          align: 'center',
          uppercase: false,
          letterSpacing: 1,
        },
        isVariable: true,
        variableKey: 'recipientName',
      },
      {
        id: 'min_desc',
        type: 'text',
        x: 560,
        y: 530,
        width: 800,
        height: 80,
        visible: true,
        text: 'for demonstrating outstanding performance, exceptional work ethic, and successful completion of\n{{courseName}}',
        style: {
          fontSize: 14,
          fontWeight: 'normal',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#475569',
          align: 'center',
          uppercase: false,
          letterSpacing: 0.5,
        },
        isVariable: true,
        variableKey: 'courseName',
      },
      {
        id: 'date',
        type: 'text',
        x: 280,
        y: 660,
        width: 250,
        height: 30,
        visible: true,
        text: '{{date}}',
        style: {
          fontSize: 14,
          fontWeight: 'normal',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#111827',
          align: 'center',
          uppercase: false,
          letterSpacing: 0,
        },
        isVariable: true,
        variableKey: 'date',
      },
      {
        id: 'min_date_line',
        type: 'text',
        x: 280,
        y: 700,
        width: 250,
        height: 20,
        visible: true,
        text: 'DATE OF THE CERTIFICATE',
        style: {
          fontSize: 10,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#94a3b8',
          align: 'center',
          uppercase: true,
          letterSpacing: 1,
        },
        isVariable: false,
      },
      {
        id: 'issuerName',
        type: 'text',
        x: 840,
        y: 660,
        width: 250,
        height: 30,
        visible: true,
        text: '{{issuerName}}',
        style: {
          fontSize: 15,
          fontWeight: 'semibold',
          fontStyle: 'normal',
          fontFamily: 'Montserrat',
          color: '#111827',
          align: 'center',
          uppercase: false,
          letterSpacing: 0,
        },
        isVariable: true,
        variableKey: 'issuerName',
      },
      {
        id: 'issuerTitle',
        type: 'text',
        x: 840,
        y: 700,
        width: 250,
        height: 20,
        visible: true,
        text: '{{issuerTitle}}',
        style: {
          fontSize: 10,
          fontWeight: 'bold',
          fontStyle: 'normal',
          fontFamily: 'Inter',
          color: '#94a3b8',
          align: 'center',
          uppercase: true,
          letterSpacing: 1,
        },
        isVariable: true,
        variableKey: 'issuerTitle',
      },
      {
        id: 'min_badge',
        type: 'badge',
        x: 920,
        y: 220,
        width: 120,
        height: 120,
        visible: true,
        badgeType: 'gold_seal',
        color: '#eab308',
      },
    ],
  },
];
